bsp: u-boot-fio: imx8mm-lpddr4-evk-sec: disable CONFIG_DISTRO_DEFAULTS
Fix building error [1] by disabling unused CONFIG_DISTRO_DEFAULTS.

[1]
include/config_distro_bootcmd.h:292:2: error: expected ‘}’ before ‘BOOT_TARGET_DEVICES_references_USB_without_CONFIG_CMD_USB’
  292 |  BOOT_TARGET_DEVICES_references_USB_without_CONFIG_CMD_USB
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/config_distro_bootcmd.h:292:2: note: in definition of macro ‘BOOTENV_DEV_NAME_USB’
  292 |  BOOT_TARGET_DEVICES_references_USB_without_CONFIG_CMD_USB
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/configs/imx8mm_evk.h:90:2: note: in expansion of macro ‘BOOTENV_DEV_NAME’
   90 |  func(USB, usb, 0) \
      |  ^~~~
...

Signed-off-by: Oleksandr Suvorov <oleksandr.suvorov@foundries.io>